version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: elnurat/foodgram-backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    restart: on-failure

  frontend:
    container_name: frontend
    image: elnurat/foodgram-frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    restart: on-failure

  gateway:
    image: elnurat/foodgram-gateway
    env_file: .env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static:/static
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    restart: on-failure